/**
 * insight_sync.ts — Insight synchronizer v2 (Claude semantic judgment version)
 *
 * Architecture:
 *   - Code = flow framework + format spec + Notion write
 *   - Claude = smart judgment layer (determine insight, distill content, generate cloze)
 *   - NEVER use keyword matching, rule judgment, or string truncation
 */

import { TIMELINE_BUFFER_PATH } from "../_shared/paths.ts";
import { getTs, getDisplay, getHhmm } from "../_shared/time_utils.ts";
import { appendJsonl } from "../_shared/jsonl_buffer.ts";

export const BUFFER_PATH = TIMELINE_BUFFER_PATH;

export interface InsightRecord {
  ts: string;
  ts_display: string;
  pid: string;
  summary: string;
  signal: string;
  synced_to_startt: boolean;
}

/**
 * Write to local JSONL buffer (execute immediately, don't wait for Notion).
 */
export async function writeToBuffer(
  pid: string,
  insightSummary: string,
  signal = "💡 收获",
): Promise<InsightRecord> {
  const record: InsightRecord = {
    ts: getTs(),
    ts_display: getDisplay(),
    pid,
    summary: insightSummary.slice(0, 20),
    signal,
    synced_to_startt: false,
  };

  await appendJsonl(BUFFER_PATH, record, "insight_sync");

  return record;
}

/**
 * Build progress block content for STARTT document T section.
 * All content is generated by Claude intelligently; code only handles format.
 *
 * @param insightSummary - Claude-distilled one-line conclusion (<20 chars)
 * @param insightDetail  - Claude-written full knowledge point (3-5 lines)
 * @param flashcardBlank - Claude-generated cloze question
 */
export function buildProgressBlock(
  insightSummary: string,
  insightDetail: string,
  flashcardBlank: string,
): string {
  const hhmm = getHhmm();
  const display = getDisplay();
  return `
> 💡 **${hhmm} · 收获：${insightSummary}**

>> 📌 ${insightDetail}

>> 🎴 填空：${flashcardBlank}

>> 🕐 记录时间：${display} (UTC+8)
`;
}

// ============================================================
// Claude insight sync protocol
// ============================================================

export const CLAUDE_INSIGHT_PROTOCOL = `
【收获同步协议·Claude执行标准】

Step 1·Claude语义判断（禁止关键词匹配）
  问自己：用户是否真正理解了某个原理？是认知跃迁还是礼貌回应？
  → 是真收获：进入Step 2
  → 是礼貌回应：不触发，继续正常对话

Step 2·Claude提炼三层内容
  - 结论（<20字）：最精华的那句话，名词短语
  - 完整知识点（3~5行）：为什么是这样，有什么意义
  - 填空题（含___）：让用户下次主动回忆的题目

Step 3·代码执行写入
  import { writeToBuffer, buildProgressBlock } from "./insight_sync.ts";
  await writeToBuffer(currentPid, insightSummary);
  const block = buildProgressBlock(insightSummary, insightDetail, flashcardBlank);

Step 4·Notion写入（追加到当前STARTT文档T区块）
  Notion:notion-update-page(
      command="update_content",
      page_id=current_startt_page_id,
      content_updates=[{
        old_str: "## ✅ T · 已澄清需求",
        new_str: "## ✅ T · 已澄清需求\n" + block
      }]
  )

【禁止的写法】
  ❌ if "哦" in user_msg: writeInsight()  ← 关键词匹配
  ❌ insight = userMsg.slice(0, 20)       ← 截断≠提炼
  ❌ 直接把用户原话存进去                   ← 未经大模型加工
`;
